services:
  http:
    build:
      context: ./
      dockerfile: ./t0d0d0d0/http/Dockerfile
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      SECRET_KEY: ${SECRET_KEY}
      RABBIT_URL: ${RABBIT_URL}
    network_mode: host
    image: docker.io/chesnokdeep/t0:http

  bot:
    build:
      context: ./
      dockerfile: ./t0d0d0d0/bot/Dockerfile
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      RABBIT_URL: ${RABBIT_URL}
      BOT_TOKEN: ${BOT_TOKEN}
    network_mode: host
    image: docker.io/chesnokdeep/t0:bot

  frontend:
    build:
      context: ./
      dockerfile: ./t0d0d0d0/frontend/Dockerfile
    network_mode: host
    image: docker.io/chesnokdeep/t0:frontend

  nginx:
    build:
      context: ./deploy/nginx
      dockerfile: ./Dockerfile
    network_mode: host
    image: docker.io/chesnokdeep/t0:nginx

  notyfier:
    build:
      context: ./
      dockerfile: ./t0d0d0d0/notyfier/Dockerfile
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      RABBIT_URL: ${RABBIT_URL}
    network_mode: host
    image: docker.io/chesnokdeep/t0:notyfier

  sheduler:
    build:
      context: ./
      dockerfile: ./t0d0d0d0/sheduler/Dockerfile
    environment:
      RABBIT_URL: ${RABBIT_URL}
    network_mode: host
    image: docker.io/chesnokdeep/t0:sheduler


networks:
  appnetwork:
    driver: bridge
