services:
  http:
    build:
      context: ./
      dockerfile: ./t0d0d0d0/http/Dockerfile
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      SECRET_KEY: ${SECRET_KEY}
      RABBIT_URL: ${RABBIT_URL}
    network_mode: host

  bot:
    build:
      context: ./
      dockerfile: ./t0d0d0d0/bot/Dockerfile
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      RABBIT_URL: ${RABBIT_URL}
      BOT_TOKEN: ${BOT_TOKEN}
    network_mode: host

  frontend:
    build:
      context: ./
      dockerfile: ./t0d0d0d0/frontend/Dockerfile
    network_mode: host

  nginx:
    build:
      context: ./deploy/nginx
      dockerfile: ./Dockerfile
    network_mode: host

  notyfier:
    build:
      context: ./
      dockerfile: ./t0d0d0d0/notyfier/Dockerfile
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      RABBIT_URL: ${RABBIT_URL}
    network_mode: host

  sheduler:
    build:
      context: ./
      dockerfile: ./t0d0d0d0/sheduler/Dockerfile
    environment:
      RABBIT_URL: ${RABBIT_URL}
    network_mode: host


networks:
  appnetwork:
    driver: bridge
