apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
      - name: bot
        image: docker.io/chesnokdeep/t0:bot
        env:
        - name: POSTGRES_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: postgres_url
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: redis_host
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: redis_port
        - name: RABBIT_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: rabbit_url
        - name: BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: bot_token