apiVersion: apps/v1
kind: Deployment
metadata:
  name: http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http
  template:
    metadata:
      labels:
        app: http
    spec:
      containers:
      - name: http
        image: docker.io/chesnokdeep/t0:http
        env:
        - name: POSTGRES_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: postgres_url
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: redis_host
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: redis_port
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: secret_key
        - name: RABBIT_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: rabbit_url